 const data =[
[{
id:1000,
bookName:"anuwarul-quarn-1",
priceMain:10,
priceNote:7,
discountPriceMaim:7,
discountPriceNote:7,
prokasoni:'Islamia-prokasoni',
description:'learning book',
optional:'null',
image:"",
quantity:4,
}],
[{
id:2000,
bookName:"mislim",
priceMain:10,
priceNote:7,
discountPriceMaim:7,
discountPriceNote:7,
prokasoni:'Islamia-prokasoni',
description:'learning book',
optional:'null',
image:"",
quantity:4,
}],
[{
id:3000,
bookName:"Bangla",
priceMain:10,
priceNote:7,
discountPriceMaim:7,
discountPriceNote:7,
prokasoni:'Islamia-prokasoni',
description:'learning book',
optional:'null',
image:"",
quantity:4,
}],
[{
id:4000,
bookName:"Bangla",
priceMain:10,
priceNote:7,
discountPriceMaim:7,
discountPriceNote:7,
prokasoni:'Befaq-prokasoni',
description:'learning book',
optional:'null',
image:"",
quantity:4,
}],
[{
id:4000,
bookName:"Bangla",
priceMain:10,
priceNote:7,
discountPriceMaim:7,
discountPriceNote:7,
prokasoni:'Islamia-prokasoni',
description:'learning book',
optional:'null',
image:"",
quantity:4,
}]
];
export function libraryData(){
  return data;
};`